name: "Chat Moderator Git Action"
description: "Automation of a chat moderator"
author: "Tatenda Chinyamakobvu" 
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'box'
  color: 'blue'